zuul:
  ignoredPatterns: /trace/**,/trace,/politeness,/politeness/**
  routes:
    web: /*
    web_all: /**
    all: /
  debug:
    request: true

server.port: 9999
debug: true
logging.level.org.springframework.web: DEBUG
logging.level.at.ac.wu.web.crawlers.thesis: DEBUG
#logging.level.org.infinispan: TRACE

#defines user for monitoring endpoints
security:
  user:
    name: monuser
    password: monuser
    role: ACTRADMIN

management:
  port: 8081
  #address: 127.0.0.1 #only reachable from localhost
  security:
    enabled: true
    roles: ACTRADMIN
  context-path: /monitor
  #curl -u monuser:monuser localhost:8081/monitor/trace

endpoints:
  trace:
    enabled: true
    sensitive: true
  info:
    enabled: true
    sensitive: true

spring:
  devtools:
    restart:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

crawler.politeness.timeout: 0

politeness:
  domains:
    - domain: derstandard.at
      delay: 100
    - domain: sport.orf.at
      delay: 5000
  use-default: false
  default-domain:
    domain: default
    delay: 5555
  jmx-domain: politenessCache
  memory: 100000
  delay-jmx-domain: delayCache

page:
  cache:
#    directory: define custom directory for cache persistence
    jmx-domain: pageCache
    memory: 1000000
    threads: 4